import Head from "next/head"
import Banner from "../components/banner"
import Card from "../components/card"
import Image from "next/image"

import styles from "../styles/Home.module.css"

export default function Home() {
  const handleOnBannerBtnClick = () => console.log("Hi from banner button")

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        <Card
          name="Darkhorse Coffee"
          imgUrl="/static/hero-image.png"
          href="/coffee-store/darkhorse-coffee"
          alt="hero image"
        />
      </main>
    </div>
  )
}
